# Generated by Django 3.2.9 on 2022-11-13 22:11

from django.db import migrations, models
import utils.rename


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0172_auto_20221114_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_one',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True, unique=True, verbose_name='Второй email'),
        ),
        migrations.AddField(
            model_name='user',
            name='workWebsite_one',
            field=models.URLField(blank=True, null=True, verbose_name='Второй сайт'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=utils.rename.Rename.rename, verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bg',
            field=models.ImageField(blank=True, null=True, upload_to=utils.rename.Rename.rename, verbose_name='Задний фон'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$kFtrETtjurvOcsQLRgXneH$S4ldwC/h4lUCbBzCNYjyF0jrHvIq1qCZ14Ll3mKh9so=', max_length=128, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='image',
            field=models.ImageField(blank=True, upload_to=utils.rename.Rename.rename, verbose_name='Изображение'),
        ),
    ]
