# Generated by Django 3.2.9 on 2022-11-15 19:42

from django.db import migrations, models
import utils.rename


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0174_auto_20221115_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_one',
        ),
        migrations.RemoveField(
            model_name='user',
            name='workWebsite_one',
        ),
        migrations.AddField(
            model_name='user',
            name='otherWebsite',
            field=models.URLField(blank=True, null=True, verbose_name='Другой любой сайт'),
        ),
        migrations.AddField(
            model_name='user',
            name='workEmail',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Рабочий email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=utils.rename.Rename.rename, verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bg',
            field=models.ImageField(blank=True, null=True, upload_to=utils.rename.Rename.rename, verbose_name='Задний фон'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$doxHWjG34OFNkNO5cfIvbu$Jeq4sYi+y2cfq9/NMndzUKOIq/majnXDgo637qaQld0=', max_length=128, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='image',
            field=models.ImageField(blank=True, upload_to=utils.rename.Rename.rename, verbose_name='Изображение'),
        ),
    ]
