version: "3.8"

services:
  web:
      build: .
      restart: always
      command: sh -c "python manage.py collectstatic --no-input && python manage.py migrate &&
        gunicorn -w 7 -b 0.0.0.0:8000 core.wsgi --reload"
      volumes:
          - .:/app
          - ./media:/app/media/
          - ./static:/app/static/
      ports:
          - "8000:8000"
      depends_on:
          - pgdb

  pgdb:
    image: postgres:latest
    container_name: pgdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=temir
      - POSTGRES_USER=temir_user
      - POSTGRES_PASSWORD=temir_123
        #      - POSTGRES_DB=temir_backend
        #      - POSTGRES_USER=hikki
        #      - POSTGRES_PASSWORD=adi

  nginx:
      image: linuxserver/swag
      #      image: nginx:latest
      restart: always
      environment:
          - PUID=1000
          - PGID=1000
          - TZ=Asia/Bishkek
          - URL=temir.ae
          - SUBDOMAINS=api
          - VALIDATION=http
          - ONLY_SUBDOMAINS=true
          - STAGING=false
      depends_on:
          - web
      ports:
          - "80:80"
          - "443:443"
      volumes:
          - ./nginx/nginx.conf:/config/nginx/site-confs/default
          - ./media:/usr/media/
          - lets:/config/keys/
          - ./static:/usr/static/

volumes:
  postgres_data:
  lets:
