#<<<<<<< HEAD
# Generated by Django 4.0.3 on 2022-04-09 13:46
#=======
# Generated by Django 4.0.1 on 2022-04-01 17:35
#>>>>>>> 9b9b977156987a4cb61a8a8ccaffed6c4faf8943

from django.db import migrations, models
import utils.rename


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_alter_card_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.ImageField(upload_to=utils.rename.Rename.rename, verbose_name='Фото'),
        ),
    ]
